/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#ifdef HILDONIZED
#include <libosso.h>
#include <hildon-widgets/hildon-app.h>
#include <hildon-widgets/hildon-appview.h>
#endif

#include "callbacks.h"
#include "interface.h"
#include "support.h"
#include "appdata.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

AppData *
create_window_main (AppData * appdata_in)
{

	AppData *appdata = NULL;
	appdata = (AppData *) appdata_in;

	/* Widgets which are not needed to be accessed outside */
	GtkWidget *vbox_main;
	GtkWidget *vbox_info;
	GtkWidget *hbox1;
	GtkWidget *button_clear;
	GtkWidget *label8;
	GtkAdjustment *spinbutton_count_adj;
	GtkWidget *button_start;
	GtkWidget *alignment1;
	GtkWidget *hbox2;
	GtkWidget *image1;
	GtkWidget *label6;
	GtkWidget *scrolledwindow1;
	GtkWidget *image2;
	GtkWidget *frame1;
	GtkWidget *alignment2;
	GtkWidget *vbox_entrys;
	GtkAdjustment *spinbutton_entrys_adj;
	GtkWidget *label3;
	GtkWidget *frame2;
	GtkWidget *alignment3;
	GtkWidget *vbox_buttons;
	GSList *radiobutton_buttons_1_group;
	GtkWidget *label4;
	GtkWidget *frame3;
	GtkWidget *alignment4;
	GtkWidget *vbox_text;
	GtkWidget *label9;
	GtkWidget *frame4;
	GtkWidget *alignment5;
	GtkWidget *vbox_drawing;
	GtkWidget *label10;
	GtkWidget *scrolledwindow2;
	GtkWidget *image3;

#ifdef HILDONIZED
	/* maemo version */
	/* Create the hildon application and setup the title */
	appdata->app = HILDON_APP (hildon_app_new ());
	hildon_app_set_title (appdata->app, "GtkPerf");

	/* Create HildonAppView and set it to HildonApp */
	appdata->window_main = HILDON_APPVIEW (hildon_appview_new (NULL));
	hildon_app_set_appview (appdata->app, appdata->window_main);
	gtk_widget_show (GTK_WIDGET (appdata->app));

#else
	/* normal GTK+ version */
	appdata->window_main = gtk_window_new (GTK_WINDOW_TOPLEVEL);
	gtk_window_set_title (GTK_WINDOW (appdata->window_main),
			      _("GtkPerf"));
	gtk_window_set_default_size (GTK_WINDOW (appdata->window_main), 500,
				     300);
	gtk_widget_show(appdata->window_main);
	
#endif

	vbox_main = gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
	gtk_widget_show (vbox_main);
	gtk_container_add (GTK_CONTAINER (appdata->window_main), vbox_main);

	appdata->notebook_main = GTK_NOTEBOOK (gtk_notebook_new ());
	gtk_widget_show (GTK_WIDGET (appdata->notebook_main));
	gtk_box_pack_start (GTK_BOX (vbox_main),
			    GTK_WIDGET (appdata->notebook_main), TRUE, TRUE,
			    0);

	vbox_info = gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
	gtk_widget_show (vbox_info);
	gtk_container_add (GTK_CONTAINER (appdata->notebook_main), vbox_info);
	hbox1 = gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 10);
	gtk_widget_show (hbox1);
	gtk_box_pack_start (GTK_BOX (vbox_info), hbox1, FALSE, TRUE, 4);

	button_clear = gtk_button_new_with_label ("gtk-clear");
	gtk_widget_show (button_clear);
	gtk_box_pack_start (GTK_BOX (hbox1), button_clear, FALSE, FALSE, 0);

	label8 = gtk_label_new (_("Test rounds:"));
	gtk_widget_show (label8);
	gtk_box_pack_start (GTK_BOX (hbox1), label8, FALSE, FALSE, 0);

	spinbutton_count_adj = gtk_adjustment_new (10, 0, 10000, 1, 10, 10);
	appdata->spinbutton_count =
		gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_count_adj), 1,
				     0);
	gtk_widget_show (appdata->spinbutton_count);
	gtk_box_pack_start (GTK_BOX (hbox1), appdata->spinbutton_count, FALSE,
			    TRUE, 0);
	gtk_widget_set_size_request (appdata->spinbutton_count, 100, -1);
	appdata->combobox_testtype = gtk_combo_box_text_new ();
	gtk_widget_show (appdata->combobox_testtype);
	gtk_box_pack_start (GTK_BOX (hbox1), appdata->combobox_testtype, TRUE,
			    TRUE, 0);
	gtk_combo_box_text_append_text (GTK_COMBO_BOX_TEXT (appdata->combobox_testtype),  
				   _("Test All"));
	gtk_combo_box_text_append_text (GTK_COMBO_BOX_TEXT (appdata->combobox_testtype), 
				   _("GtkEntry"));
	gtk_combo_box_text_append_text (GTK_COMBO_BOX_TEXT (appdata->combobox_testtype), 
				   _("GtkComboBox"));
	gtk_combo_box_text_append_text (GTK_COMBO_BOX_TEXT (appdata->combobox_testtype), 
				   _("GtkComboBoxEntry"));
	gtk_combo_box_text_append_text (GTK_COMBO_BOX_TEXT (appdata->combobox_testtype), 
				   _("GtkSpinButton"));
	gtk_combo_box_text_append_text (GTK_COMBO_BOX_TEXT (appdata->combobox_testtype), 
				   _("GtkProgressBar"));
	gtk_combo_box_text_append_text (GTK_COMBO_BOX_TEXT (appdata->combobox_testtype), 
				   _("GtkToggleButton"));
	gtk_combo_box_text_append_text (GTK_COMBO_BOX_TEXT (appdata->combobox_testtype), 
				   _("GtkCheckButton"));
	gtk_combo_box_text_append_text (GTK_COMBO_BOX_TEXT (appdata->combobox_testtype), 
				   _("GtkRadioButton"));
	gtk_combo_box_text_append_text (GTK_COMBO_BOX_TEXT (appdata->combobox_testtype), 
				   _("GtkTextView - Add text"));
	gtk_combo_box_text_append_text (GTK_COMBO_BOX_TEXT (appdata->combobox_testtype), 
				   _("GtkTextView - Scroll"));
	gtk_combo_box_text_append_text (GTK_COMBO_BOX_TEXT (appdata->combobox_testtype), 
				   _("GtkDrawingArea - Lines"));
	gtk_combo_box_text_append_text (GTK_COMBO_BOX_TEXT (appdata->combobox_testtype), 
				   _("GtkDrawingArea - Circles"));
	gtk_combo_box_text_append_text (GTK_COMBO_BOX_TEXT (appdata->combobox_testtype), 
				   _("GtkDrawingArea - Text"));
	gtk_combo_box_text_append_text (GTK_COMBO_BOX_TEXT (appdata->combobox_testtype),
				   _("GtkDrawingArea - Pixbufs"));
	
	button_start = gtk_button_new ();
	gtk_widget_show (button_start);
	gtk_box_pack_start (GTK_BOX (hbox1), button_start, FALSE, FALSE, 0);

	hbox2 = gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 2);
	gtk_widget_show (hbox2);
	gtk_container_add (GTK_CONTAINER (button_start), hbox2);
	image1 = gtk_image_new_from_icon_name ("gtk-execute",
					   GTK_ICON_SIZE_BUTTON);
	gtk_widget_show (image1);
	gtk_box_pack_start (GTK_BOX (hbox2), image1, FALSE, FALSE, 0);

	label6 = gtk_label_new_with_mnemonic (_("Start"));
	gtk_widget_show (label6);
	gtk_box_pack_start (GTK_BOX (hbox2), label6, FALSE, FALSE, 0);

	scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
	gtk_widget_show (scrolledwindow1);
	gtk_box_pack_start (GTK_BOX (vbox_info), scrolledwindow1, TRUE, TRUE,
			    2);
	gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1),
					GTK_POLICY_NEVER,
					GTK_POLICY_AUTOMATIC);
	gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW
					     (scrolledwindow1),
					     GTK_SHADOW_IN);
	appdata->textview_info = gtk_text_view_new ();
	gtk_widget_show (appdata->textview_info);
	gtk_container_add (GTK_CONTAINER (scrolledwindow1),
			   appdata->textview_info);
	gtk_container_set_border_width (GTK_CONTAINER
					(appdata->textview_info), 4);
	gtk_text_view_set_editable (GTK_TEXT_VIEW (appdata->textview_info),
				    FALSE);
	gtk_text_view_set_wrap_mode (GTK_TEXT_VIEW (appdata->textview_info),
				     GTK_WRAP_WORD);
	gtk_text_view_set_cursor_visible (GTK_TEXT_VIEW
					  (appdata->textview_info), FALSE);

	image2 = gtk_image_new_from_icon_name ("gtk-dialog-info",
					   GTK_ICON_SIZE_BUTTON);
	gtk_widget_show (image2);
	gtk_notebook_set_tab_label (GTK_NOTEBOOK (appdata->notebook_main),
				    gtk_notebook_get_nth_page (GTK_NOTEBOOK
							       (appdata->
								notebook_main),
							       0), image2);
	frame1 = gtk_frame_new (NULL);
	gtk_widget_show (frame1);
	gtk_container_add (GTK_CONTAINER (appdata->notebook_main), frame1);
	gtk_container_set_border_width (GTK_CONTAINER (frame1), 10);
	gtk_frame_set_shadow_type (GTK_FRAME (frame1), GTK_SHADOW_NONE);

	alignment2 = gtk_alignment_new (0.5, 0.2, 0.3, 0.3);
	gtk_widget_show (alignment2);
	gtk_container_add (GTK_CONTAINER (frame1), alignment2);

	vbox_entrys = gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
	gtk_widget_show (vbox_entrys);
	gtk_container_add (GTK_CONTAINER (alignment2), vbox_entrys);
	appdata->entry_entrys = gtk_entry_new ();
	gtk_widget_show (appdata->entry_entrys);
	gtk_box_pack_start (GTK_BOX (vbox_entrys), appdata->entry_entrys,
			    FALSE, FALSE, 0);

	appdata->combobox_entrys = gtk_combo_box_text_new ();
	gtk_widget_show (appdata->combobox_entrys);
	gtk_box_pack_start (GTK_BOX (vbox_entrys), appdata->combobox_entrys,
			    TRUE, TRUE, 0);

	appdata->comboboxentry_entrys = gtk_combo_box_text_new_with_entry ();
	gtk_widget_show (appdata->comboboxentry_entrys);
	gtk_box_pack_start (GTK_BOX (vbox_entrys),
			    appdata->comboboxentry_entrys, TRUE, TRUE, 0);

	spinbutton_entrys_adj = gtk_adjustment_new (1, 0, 10000, 1, 10, 10);
	appdata->spinbutton_entrys =
		gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_entrys_adj),
				     1, 0);
	gtk_widget_show (appdata->spinbutton_entrys);
	gtk_box_pack_start (GTK_BOX (vbox_entrys), appdata->spinbutton_entrys,
			    FALSE, FALSE, 0);

	appdata->progressbar_entrys = gtk_progress_bar_new ();
	gtk_widget_show (appdata->progressbar_entrys);
	gtk_box_pack_start (GTK_BOX (vbox_entrys),
			    appdata->progressbar_entrys, FALSE, FALSE, 0);
	gtk_progress_bar_set_text (GTK_PROGRESS_BAR
				   (appdata->progressbar_entrys),
				   _("GtkProgressBar"));

	appdata->label_entrys = gtk_label_new (_("Entrys"));
	gtk_widget_show (appdata->label_entrys);
	gtk_frame_set_label_widget (GTK_FRAME (frame1),
				    appdata->label_entrys);
	gtk_label_set_use_markup (GTK_LABEL (appdata->label_entrys), TRUE);
	gtk_misc_set_padding (GTK_MISC (appdata->label_entrys), 10, 0);
	label3 = gtk_label_new (_("Entrys"));
	gtk_widget_show (label3);
	gtk_notebook_set_tab_label (GTK_NOTEBOOK (appdata->notebook_main),
				    gtk_notebook_get_nth_page (GTK_NOTEBOOK
							       (appdata->
								notebook_main),
							       1), label3);

	frame2 = gtk_frame_new (NULL);
	gtk_widget_show (frame2);
	gtk_container_add (GTK_CONTAINER (appdata->notebook_main), frame2);
	gtk_container_set_border_width (GTK_CONTAINER (frame2), 10);
	gtk_frame_set_shadow_type (GTK_FRAME (frame2), GTK_SHADOW_NONE);

	alignment3 = gtk_alignment_new (0.5, 0.2, 0.3, 0);
	gtk_widget_show (alignment3);
	gtk_container_add (GTK_CONTAINER (frame2), alignment3);

	vbox_buttons = gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
	gtk_widget_show (vbox_buttons);
	gtk_container_add (GTK_CONTAINER (alignment3), vbox_buttons);
	appdata->togglebutton_buttons =
		gtk_toggle_button_new_with_mnemonic (_("GtkToggleButton"));
	gtk_widget_show (appdata->togglebutton_buttons);
	gtk_box_pack_start (GTK_BOX (vbox_buttons),
			    appdata->togglebutton_buttons, FALSE, FALSE, 0);

	appdata->checkbutton_buttons =
		gtk_check_button_new_with_mnemonic (_("GtkCheckButton"));
	gtk_widget_show (appdata->checkbutton_buttons);
	gtk_box_pack_start (GTK_BOX (vbox_buttons),
			    appdata->checkbutton_buttons, FALSE, FALSE, 0);

	radiobutton_buttons_1_group = NULL;
	appdata->radiobutton_buttons_1 =
		gtk_radio_button_new_with_mnemonic (NULL,
						    _("GtkRadioButton 1"));
	gtk_widget_show (appdata->radiobutton_buttons_1);
	gtk_box_pack_start (GTK_BOX (vbox_buttons),
			    appdata->radiobutton_buttons_1, FALSE, FALSE, 0);
	gtk_radio_button_set_group (GTK_RADIO_BUTTON
				    (appdata->radiobutton_buttons_1),
				    radiobutton_buttons_1_group);
	radiobutton_buttons_1_group =
		gtk_radio_button_get_group (GTK_RADIO_BUTTON
					    (appdata->radiobutton_buttons_1));

	appdata->radiobutton_buttons_2 =
		gtk_radio_button_new_with_mnemonic (NULL,
						    _("GtkRadioButton 2"));
	gtk_widget_show (appdata->radiobutton_buttons_2);
	gtk_box_pack_start (GTK_BOX (vbox_buttons),
			    appdata->radiobutton_buttons_2, FALSE, FALSE, 0);
	gtk_radio_button_set_group (GTK_RADIO_BUTTON
				    (appdata->radiobutton_buttons_2),
				    radiobutton_buttons_1_group);
	radiobutton_buttons_1_group =
		gtk_radio_button_get_group (GTK_RADIO_BUTTON
					    (appdata->radiobutton_buttons_2));
	appdata->label_buttons = gtk_label_new (_("Buttons"));
	gtk_widget_show (appdata->label_buttons);
	gtk_frame_set_label_widget (GTK_FRAME (frame2),
				    appdata->label_buttons);
	gtk_label_set_use_markup (GTK_LABEL (appdata->label_buttons), TRUE);
	gtk_misc_set_padding (GTK_MISC (appdata->label_buttons), 10, 0);

	label4 = gtk_label_new (_("Buttons"));
	gtk_widget_show (label4);
	gtk_notebook_set_tab_label (GTK_NOTEBOOK (appdata->notebook_main),
				    gtk_notebook_get_nth_page (GTK_NOTEBOOK
							       (appdata->
								notebook_main),
							       2), label4);

	frame3 = gtk_frame_new (NULL);
	gtk_widget_show (frame3);
	gtk_container_add (GTK_CONTAINER (appdata->notebook_main), frame3);
	gtk_container_set_border_width (GTK_CONTAINER (frame3), 10);
	gtk_frame_set_shadow_type (GTK_FRAME (frame3), GTK_SHADOW_NONE);

	alignment4 = gtk_alignment_new (0.5, 0.5, 1, 1);
	gtk_widget_show (alignment4);
	gtk_container_add (GTK_CONTAINER (frame3), alignment4);
	gtk_container_set_border_width (GTK_CONTAINER (alignment4), 5);

	vbox_text = gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
	gtk_widget_show (vbox_text);
	gtk_container_add (GTK_CONTAINER (alignment4), vbox_text);
	appdata->scrolledwindow_text = gtk_scrolled_window_new (NULL, NULL);
	gtk_widget_show (appdata->scrolledwindow_text);
	gtk_box_pack_start (GTK_BOX (vbox_text), appdata->scrolledwindow_text,
			    TRUE, TRUE, 0);
	gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW
					(appdata->scrolledwindow_text),
					GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);
	gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW
					     (appdata->scrolledwindow_text),
					     GTK_SHADOW_IN);

	appdata->textview_text = gtk_text_view_new ();
	gtk_widget_show (appdata->textview_text);
	gtk_container_add (GTK_CONTAINER (appdata->scrolledwindow_text),
			   appdata->textview_text);
	gtk_text_view_set_editable (GTK_TEXT_VIEW (appdata->textview_text),
				    FALSE);
	gtk_text_view_set_wrap_mode (GTK_TEXT_VIEW (appdata->textview_text),
				     GTK_WRAP_WORD);
	gtk_text_view_set_cursor_visible (GTK_TEXT_VIEW
					  (appdata->textview_text), FALSE);

	appdata->label_text = gtk_label_new (_("GtkTextView"));
	gtk_widget_show (appdata->label_text);
	gtk_frame_set_label_widget (GTK_FRAME (frame3), appdata->label_text);
	gtk_label_set_use_markup (GTK_LABEL (appdata->label_text), TRUE);
	gtk_misc_set_padding (GTK_MISC (appdata->label_text), 10, 0);

	label9 = gtk_label_new (_("Text"));
	gtk_widget_show (label9);
	gtk_notebook_set_tab_label (GTK_NOTEBOOK (appdata->notebook_main),
				    gtk_notebook_get_nth_page (GTK_NOTEBOOK
							       (appdata->
								notebook_main),
							       3), label9);
	frame4 = gtk_frame_new (NULL);
	gtk_widget_show (frame4);
	gtk_container_add (GTK_CONTAINER (appdata->notebook_main), frame4);
	gtk_container_set_border_width (GTK_CONTAINER (frame4), 10);
	gtk_frame_set_shadow_type (GTK_FRAME (frame4), GTK_SHADOW_NONE);

	alignment5 = gtk_alignment_new (0.5, 0.5, 0.95, 0.9);
	gtk_widget_show (alignment5);
	gtk_container_add (GTK_CONTAINER (frame4), alignment5);

	vbox_drawing = gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
	gtk_widget_show (vbox_drawing);
	gtk_container_add (GTK_CONTAINER (alignment5), vbox_drawing);

	appdata->drawingarea_drawing = gtk_drawing_area_new ();
	gtk_widget_show (appdata->drawingarea_drawing);
	gtk_box_pack_start (GTK_BOX (vbox_drawing),
			    appdata->drawingarea_drawing, TRUE, TRUE, 0);

	appdata->label_drawing = gtk_label_new (_("GtkDrawingArea"));
	gtk_widget_show (appdata->label_drawing);
	gtk_frame_set_label_widget (GTK_FRAME (frame4),
				    appdata->label_drawing);
	gtk_label_set_use_markup (GTK_LABEL (appdata->label_drawing), TRUE);
	gtk_misc_set_padding (GTK_MISC (appdata->label_drawing), 10, 0);

	label10 = gtk_label_new (_("Drawing"));
	gtk_widget_show (label10);
	gtk_notebook_set_tab_label (GTK_NOTEBOOK (appdata->notebook_main),
				    gtk_notebook_get_nth_page (GTK_NOTEBOOK
							       (appdata->
								notebook_main),
							       4), label10);

	scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
	gtk_widget_show (scrolledwindow2);
	gtk_container_add (GTK_CONTAINER (appdata->notebook_main),
			   scrolledwindow2);
	gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2),
					GTK_POLICY_NEVER,
					GTK_POLICY_AUTOMATIC);
	gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW
					     (scrolledwindow2),
					     GTK_SHADOW_IN);
	appdata->textview_help = gtk_text_view_new ();
	gtk_widget_show (appdata->textview_help);
	gtk_container_add (GTK_CONTAINER (scrolledwindow2),
			   appdata->textview_help);
	gtk_container_set_border_width (GTK_CONTAINER
					(appdata->textview_help), 4);
	gtk_text_view_set_editable (GTK_TEXT_VIEW (appdata->textview_help),
				    FALSE);
	gtk_text_view_set_wrap_mode (GTK_TEXT_VIEW (appdata->textview_help),
				     GTK_WRAP_WORD);

	image3 = gtk_image_new_from_icon_name ("gtk-help", GTK_ICON_SIZE_BUTTON);
	gtk_widget_show (image3);
	gtk_notebook_set_tab_label (GTK_NOTEBOOK (appdata->notebook_main),
				    gtk_notebook_get_nth_page (GTK_NOTEBOOK
							       (appdata->
								notebook_main),
							       5), image3);

	appdata->statusbar_main = gtk_statusbar_new ();
	gtk_widget_show (appdata->statusbar_main);
	gtk_box_pack_start (GTK_BOX (vbox_main), appdata->statusbar_main,
			    FALSE, FALSE, 0);

	g_signal_connect ((gpointer) appdata->window_main, "delete_event",
			  G_CALLBACK (on_window_main_delete_event), NULL);
	g_signal_connect ((gpointer) button_clear, "clicked",
			  G_CALLBACK (on_button_clear_clicked), NULL);
	g_signal_connect ((gpointer) button_start, "clicked",
			  G_CALLBACK (on_button_start_clicked), NULL);

	return appdata;
}
